=== arjamizo/java_xml/l3t1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zsk.ict.pwr.wroc.pl/zsk/dyd/did/java_xml/laboratory/lab_3/" elementFormDefault="qualified">
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
							<xs:element name="state" maxOccurs="unbounded" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="unborn"/>
										<xs:enumeration value="alive"/>
										<xs:enumeration value="dead"/>
									</xs:restriction>
									<!-- 
									<xs:attribute name="desc" type="xs:string" use="optional"/>
									http://stackoverflow.com/a/1336100/781312 can not be done. 
									-->
								</xs:simpleType>
							</xs:element>
							<xs:element name="surname" type="xs:string" maxOccurs="unbounded" minOccurs="1"/>
							<xs:element name="phone" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="operator" type="xs:string" use="required"/>
											<xs:attribute name="countryprefix" type="xs:integer" use="optional"/>
										</xs:extension>
									</xs:simpleContent> 
								</xs:complexType>
							</xs:element>



							<xs:element name="address" maxOccurs="unbounded" minOccurs="1">
								<xs:complexType>
									<xs:sequence>
														
										<xs:element name="street" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="lang" type="xs:string" use="optional"/>
													</xs:extension>
												</xs:simpleContent> 
											</xs:complexType>
										</xs:element> 
										<xs:element name="city" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="lang" type="xs:string" use="optional"/>
													</xs:extension>
												</xs:simpleContent> 
											</xs:complexType>
										</xs:element> 
										<xs:element name="country" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="lang" type="xs:string" use="optional"/>
													</xs:extension>
												</xs:simpleContent> 
											</xs:complexType>
										</xs:element>
										<xs:element name="gps" maxOccurs="unbounded" minOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="coordinates-system" type="xs:string" use="optional"/>
													</xs:extension>
												</xs:simpleContent> 
											</xs:complexType>
										</xs:element>  
									</xs:sequence>
														<xs:attribute name="type" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>


						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== arjamizo/java_xml/l3t1.xml
<?xml version="1.0" encoding="UTF-8"?> 
<employees xmlns="http://www.zsk.ict.pwr.wroc.pl/zsk/dyd/did/java_xml/laboratory/lab_3/" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="./l3t1.xsd"> 
	<employee>	 
		<name>Jan</name>
		<name>Grześ</name> 
		<state>unborn</state>
		<surname>Nowak</surname>   
		<phone operator="PLAY">600613</phone>
		<address type="temporary">
			<street lang="pl">ul. Ulicowa</street>
			<city>Wrocław</city> 
			<country>Poland</country>
			<gps coordinates-system="EPEG600613">51,17</gps>      
		</address> 
	</employee>
	<employee> 
		<name>Juan</name>
		<surname>Carlos</surname>
		<surname>De Los Parlotes</surname>   
		<surname>De Amadeo</surname>
		<phone operator="UKMOBILE" countryprefix="+44">564785634</phone>       
		<address type="permanent residence">
			<street lang="es">Calle de la Madera</street>
			<street lang="pl">ul. Drewniana</street>
			<city lang="es">Madrid</city>
			<city lang="pl">Madryt</city>
			<country lang="es">Espana</country>
			<country lang="pl">Hiszpania</country>
			<country lang="en">Spain</country>
			<gps coordinates-system="EEPG4654">40.4235066,-3.7043417</gps>
		</address>

	</employee>
</employees>
