=== arjamizo/java_xml/Lab1_task5.dtd
<!ELEMENT employees (employee*) >
<!ELEMENT employee (name+, surname+, phone?, address?) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT surname (#PCDATA) >
<!ELEMENT phone (#PCDATA) >
<!ATTLIST phone operator CDATA #IMPLIED >
<!ATTLIST phone countryprefix CDATA #IMPLIED >
<!ELEMENT address (street+, city+, country+, gps?) >
<!ATTLIST address type CDATA #IMPLIED  >
<!ELEMENT street (#PCDATA) >
<!ATTLIST street lang CDATA #IMPLIED  >
<!ELEMENT city (#PCDATA) >
<!ATTLIST city lang CDATA #IMPLIED  >
<!ELEMENT street (#PCDATA) >
<!ATTLIST street lang CDATA #IMPLIED >
<!ELEMENT country (#PCDATA) >
<!ATTLIST country lang CDATA #IMPLIED >
<!ELEMENT gps (#PCDATA) >
<!ATTLIST gps coordinates-system CDATA #IMPLIED >

=== arjamizo/java_xml/Lab1_task1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
This document requires running chrome with  - -allow-file-access-from-files paramter 
-->
<!DOCTYPE employees SYSTEM "Lab1_task5.dtd"> 
<!--<?xml-stylesheet href="Lab2_task1.xsl" type="text/xsl" ?>-->
<?xml-stylesheet href="Lab2_task3.xsl" type="text/xsl" ?>
<employees>
	<employee>	
		<name>Artur</name>
		<name>Jan</name> 
		<surname>Nowak</surname>   
		<phone operator="PLAY">123456789</phone>
		<address type="temporary">
			<street lang="pl">ul. Ulicowa</street>
			<city>Wroc≈Çaw</city> 
			<country>Poland</country>
			<gps coordinates-system="EPEG600613">51,17</gps>
		</address> 
	</employee>
	<employee> 
		<name>Juan</name>
		<surname>Carlos</surname>
		<surname>De Los Parlotes</surname>
		<surname>De Amadeo</surname>
		<phone operator="UKMOBILE" countryprefix="+44">564785634</phone> <!-- Podajemy prefix kraju w przypadku, jesli ma sie numer w innym kraju -->
		<address type="permanent residence">
			<street lang="es">Calle de la Madera</street>
			<street lang="pl">ul. Drewniana</street>
			<city lang="es">Madrid</city>
			<city lang="pl">Madryt</city>
			<country lang="es">Espana</country>
			<country lang="pl">Hiszpania</country>
			<country lang="en">Spain</country>
			<gps coordinates-system="EEPG4654">40.4235066,-3.7043417</gps>
		</address>

	</employee>
</employees>
